<?php
/**
 * Analytics Terms
 */
return [
	    'settings_group_analytics' => [
        'fi' => 'Analytiikka',
        'sv' => 'Analys',
        'en' => 'Analytics',
        'it' => 'Analisi',
        'el' => 'Αναλυτικά στοιχεία',
    ],
    'nav_analytics' => [
        'fi' => 'Analytiikka',
        'sv' => 'Analys',
        'en' => 'Analytics',
        'it' => 'Analisi',
        'el' => 'Αναλυτικά στοιχεία',
    ],
    'analytics_no_permission' => [
        'fi' => 'Sinulla ei ole oikeutta tarkastella analytiikkaa.',
        'sv' => 'Du har inte behörighet att visa analysen.',
        'en' => 'You do not have permission to view analytics.',
        'it' => 'Non hai il permesso di visualizzare le analisi.',
        'el' => 'Δεν έχετε δικαίωμα προβολής των αναλυτικών στοιχείων.',
    ],
    'analytics_eyebrow' => [
        'fi' => 'SafetyFlash Analytics',
        'sv' => 'SafetyFlash Analytics',
        'en' => 'SafetyFlash Analytics',
        'it' => 'SafetyFlash Analytics',
        'el' => 'SafetyFlash Analytics',
    ],
    'analytics_title' => [
        'fi' => 'Käyttöanalytiikka',
        'sv' => 'Användningsanalys',
        'en' => 'Usage analytics',
        'it' => 'Analisi di utilizzo',
        'el' => 'Αναλυτικά στοιχεία χρήσης',
    ],
    'analytics_subtitle' => [
        'fi' => 'Seuraa sovelluksen käyttöä, SafetyFlashien lukemista, push-ilmoitusten vaikuttavuutta ja PWA-appikäyttöä.',
        'sv' => 'Följ appanvändning, läsning av SafetyFlash, effekten av pushnotiser och PWA-användning.',
        'en' => 'Track app usage, SafetyFlash readership, push notification impact and PWA app usage.',
        'it' => 'Monitora l’utilizzo dell’app, la lettura dei SafetyFlash, l’efficacia delle notifiche push e l’uso PWA.',
        'el' => 'Παρακολουθήστε τη χρήση της εφαρμογής, την ανάγνωση SafetyFlash, την επίδραση των push ειδοποιήσεων και τη χρήση PWA.',
    ],
    'analytics_period' => [
        'fi' => 'Ajanjakso',
        'sv' => 'Period',
        'en' => 'Period',
        'it' => 'Periodo',
        'el' => 'Περίοδος',
    ],
    'analytics_days_short' => [
        'fi' => 'pv',
        'sv' => 'd',
        'en' => 'd',
        'it' => 'g',
        'el' => 'ημ.',
    ],
    'analytics_active_today' => [
        'fi' => 'Aktiiviset tänään',
        'sv' => 'Aktiva idag',
        'en' => 'Active today',
        'it' => 'Attivi oggi',
        'el' => 'Ενεργοί σήμερα',
    ],
    'analytics_active_period' => [
        'fi' => 'Aktiiviset jaksolla',
        'sv' => 'Aktiva under perioden',
        'en' => 'Active in period',
        'it' => 'Attivi nel periodo',
        'el' => 'Ενεργοί στην περίοδο',
    ],
    'analytics_page_views' => [
        'fi' => 'Sivukatselut',
        'sv' => 'Sidvisningar',
        'en' => 'Page views',
        'it' => 'Visualizzazioni pagina',
        'el' => 'Προβολές σελίδων',
    ],
    'analytics_flash_views' => [
        'fi' => 'SafetyFlash-avaukset',
        'sv' => 'SafetyFlash-visningar',
        'en' => 'SafetyFlash views',
        'it' => 'Visualizzazioni SafetyFlash',
        'el' => 'Προβολές SafetyFlash',
    ],
    'analytics_push_ctr' => [
        'fi' => 'Push CTR',
        'sv' => 'Push CTR',
        'en' => 'Push CTR',
        'it' => 'Push CTR',
        'el' => 'Push CTR',
    ],
    'analytics_pwa_users' => [
        'fi' => 'PWA-käyttäjät',
        'sv' => 'PWA-användare',
        'en' => 'PWA users',
        'it' => 'Utenti PWA',
        'el' => 'Χρήστες PWA',
    ],
    'analytics_usage_trend' => [
        'fi' => 'Käyttötrendi',
        'sv' => 'Användningstrend',
        'en' => 'Usage trend',
        'it' => 'Andamento utilizzo',
        'el' => 'Τάση χρήσης',
    ],
    'analytics_usage_trend_hint' => [
        'fi' => 'Sivukatselut, SafetyFlash-avaukset ja aktiiviset käyttäjät valitulla ajanjaksolla.',
        'sv' => 'Sidvisningar, SafetyFlash-visningar och aktiva användare under vald period.',
        'en' => 'Page views, SafetyFlash views and active users in the selected period.',
        'it' => 'Visualizzazioni pagina, SafetyFlash e utenti attivi nel periodo selezionato.',
        'el' => 'Προβολές σελίδων, προβολές SafetyFlash και ενεργοί χρήστες στην επιλεγμένη περίοδο.',
    ],
    'analytics_pwa_usage' => [
        'fi' => 'Appi vs selain',
        'sv' => 'App vs webbläsare',
        'en' => 'App vs browser',
        'it' => 'App vs browser',
        'el' => 'Εφαρμογή έναντι προγράμματος περιήγησης',
    ],
    'analytics_devices' => [
        'fi' => 'Laitteet',
        'sv' => 'Enheter',
        'en' => 'Devices',
        'it' => 'Dispositivi',
        'el' => 'Συσκευές',
    ],
    'analytics_top_pages' => [
        'fi' => 'Suosituimmat sivut',
        'sv' => 'Populäraste sidor',
        'en' => 'Top pages',
        'it' => 'Pagine principali',
        'el' => 'Κορυφαίες σελίδες',
    ],
    'analytics_push' => [
        'fi' => 'Push-ilmoitukset',
        'sv' => 'Pushnotiser',
        'en' => 'Push notifications',
        'it' => 'Notifiche push',
        'el' => 'Push ειδοποιήσεις',
    ],
    'analytics_push_sent' => [
        'fi' => 'Lähetetty',
        'sv' => 'Skickade',
        'en' => 'Sent',
        'it' => 'Inviate',
        'el' => 'Στάλθηκαν',
    ],
    'analytics_push_clicked' => [
        'fi' => 'Klikattu',
        'sv' => 'Klickade',
        'en' => 'Clicked',
        'it' => 'Cliccate',
        'el' => 'Πατήθηκαν',
    ],
    'analytics_push_opened' => [
        'fi' => 'Avattu',
        'sv' => 'Öppnade',
        'en' => 'Opened',
        'it' => 'Aperte',
        'el' => 'Ανοίχθηκαν',
    ],
    'analytics_push_open_rate' => [
        'fi' => 'Avausprosentti',
        'sv' => 'Öppningsgrad',
        'en' => 'Open rate',
        'it' => 'Tasso di apertura',
        'el' => 'Ποσοστό ανοίγματος',
    ],
    'analytics_top_flashes' => [
        'fi' => 'Katsotuimmat SafetyFlashit',
        'sv' => 'Mest visade SafetyFlash',
        'en' => 'Most viewed SafetyFlashes',
        'it' => 'SafetyFlash più visualizzati',
        'el' => 'SafetyFlash με τις περισσότερες προβολές',
    ],
    'analytics_sources' => [
        'fi' => 'Avauslähteet',
        'sv' => 'Öppningskällor',
        'en' => 'Opening sources',
        'it' => 'Fonti di apertura',
        'el' => 'Πηγές ανοίγματος',
    ],
    'analytics_worksites' => [
        'fi' => 'Työmaakohtainen käyttö',
        'sv' => 'Användning per arbetsplats',
        'en' => 'Usage by worksite',
        'it' => 'Utilizzo per cantiere',
        'el' => 'Χρήση ανά εργοτάξιο',
    ],
    'analytics_daily_activity' => [
        'fi' => 'Päivittäinen käyttö',
        'sv' => 'Daglig användning',
        'en' => 'Daily activity',
        'it' => 'Attività giornaliera',
        'el' => 'Ημερήσια δραστηριότητα',
    ],
    'analytics_daily_activity_hint' => [
        'fi' => 'Näyttää valitun ajanjakson päivittäiset tapahtumat, käyttäjät, SafetyFlash-katselut ja push-avaukset.',
        'sv' => 'Visar dagliga händelser, användare, SafetyFlash-visningar och pushöppningar för vald period.',
        'en' => 'Shows daily events, users, SafetyFlash views and push opens for the selected period.',
        'it' => 'Mostra eventi giornalieri, utenti, visualizzazioni SafetyFlash e aperture push per il periodo selezionato.',
        'el' => 'Εμφανίζει ημερήσια συμβάντα, χρήστες, προβολές SafetyFlash και ανοίγματα push για την επιλεγμένη περίοδο.',
    ],
    'analytics_user_activity' => [
        'fi' => 'Käyttäjäkohtainen käyttö',
        'sv' => 'Användning per användare',
        'en' => 'User activity',
        'it' => 'Attività per utente',
        'el' => 'Δραστηριότητα ανά χρήστη',
    ],
    'analytics_user_activity_hint' => [
        'fi' => 'Näyttää aktiivisimmat käyttäjät, lukukerrat, push-avaukset ja PWA-käytön valitulla ajanjaksolla.',
        'sv' => 'Visar de mest aktiva användarna, läsningar, pushöppningar och PWA-användning under vald period.',
        'en' => 'Shows the most active users, reads, push opens and PWA usage during the selected period.',
        'it' => 'Mostra gli utenti più attivi, le letture, le aperture push e l’uso PWA nel periodo selezionato.',
        'el' => 'Εμφανίζει τους πιο ενεργούς χρήστες, αναγνώσεις, ανοίγματα push και χρήση PWA στην επιλεγμένη περίοδο.',
    ],
    'analytics_loading' => [
        'fi' => 'Ladataan analytiikkaa…',
        'sv' => 'Laddar analys…',
        'en' => 'Loading analytics…',
        'it' => 'Caricamento analisi…',
        'el' => 'Φόρτωση αναλυτικών στοιχείων…',
    ],
    'analytics_no_data' => [
        'fi' => 'Ei dataa valitulla ajanjaksolla',
        'sv' => 'Ingen data för vald period',
        'en' => 'No data for the selected period',
        'it' => 'Nessun dato per il periodo selezionato',
        'el' => 'Δεν υπάρχουν δεδομένα για την επιλεγμένη περίοδο',
    ],
    'analytics_views' => [
        'fi' => 'Katselut',
        'sv' => 'Visningar',
        'en' => 'Views',
        'it' => 'Visualizzazioni',
        'el' => 'Προβολές',
    ],
    'analytics_users' => [
        'fi' => 'Käyttäjät',
        'sv' => 'Användare',
        'en' => 'Users',
        'it' => 'Utenti',
        'el' => 'Χρήστες',
    ],
    'analytics_avg_duration' => [
        'fi' => 'Keskimääräinen aika',
        'sv' => 'Genomsnittlig tid',
        'en' => 'Average duration',
        'it' => 'Durata media',
        'el' => 'Μέση διάρκεια',
    ],
    'analytics_read_full' => [
        'fi' => 'Luettu loppuun',
        'sv' => 'Läst till slut',
        'en' => 'Read fully',
        'it' => 'Letto completamente',
        'el' => 'Διαβάστηκε πλήρως',
    ],
    'analytics_pwa' => [
        'fi' => 'Appi',
        'sv' => 'App',
        'en' => 'App',
        'it' => 'App',
        'el' => 'Εφαρμογή',
    ],
    'analytics_browser' => [
        'fi' => 'Selain',
        'sv' => 'Webbläsare',
        'en' => 'Browser',
        'it' => 'Browser',
        'el' => 'Πρόγραμμα περιήγησης',
    ],
	    'analytics_events' => [
        'fi' => 'tapahtumaa',
        'sv' => 'händelser',
        'en' => 'events',
        'it' => 'eventi',
        'el' => 'συμβάντα',
    ],
    'analytics_user_devices' => [
        'fi' => 'käyttäjä-laitetta',
        'sv' => 'användarenheter',
        'en' => 'user devices',
        'it' => 'dispositivi utente',
        'el' => 'συσκευές χρηστών',
    ],
    'analytics_unknown' => [
        'fi' => 'Tuntematon',
        'sv' => 'Okänd',
        'en' => 'Unknown',
        'it' => 'Sconosciuto',
        'el' => 'Άγνωστο',
    ],
    'analytics_page_dashboard' => [
        'fi' => 'Dashboard',
        'sv' => 'Dashboard',
        'en' => 'Dashboard',
        'it' => 'Dashboard',
        'el' => 'Dashboard',
    ],
    'analytics_page_analytics' => [
        'fi' => 'Analytiikka',
        'sv' => 'Analys',
        'en' => 'Analytics',
        'it' => 'Analisi',
        'el' => 'Αναλυτικά στοιχεία',
    ],
    'analytics_page_list' => [
        'fi' => 'SafetyFlash-lista',
        'sv' => 'SafetyFlash-lista',
        'en' => 'SafetyFlash list',
        'it' => 'Elenco SafetyFlash',
        'el' => 'Λίστα SafetyFlash',
    ],
    'analytics_page_view' => [
        'fi' => 'SafetyFlashin tarkastelunäkymä',
        'sv' => 'SafetyFlash granskningsvy',
        'en' => 'SafetyFlash view',
        'it' => 'Vista SafetyFlash',
        'el' => 'Προβολή SafetyFlash',
    ],
    'analytics_page_settings' => [
        'fi' => 'Asetukset-sivu',
        'sv' => 'Inställningssida',
        'en' => 'Settings page',
        'it' => 'Pagina impostazioni',
        'el' => 'Σελίδα ρυθμίσεων',
    ],
    'analytics_page_feedback' => [
        'fi' => 'Palaute',
        'sv' => 'Feedback',
        'en' => 'Feedback',
        'it' => 'Feedback',
        'el' => 'Σχόλια',
    ],
    'analytics_page_updates' => [
        'fi' => 'Päivitykset',
        'sv' => 'Uppdateringar',
        'en' => 'Updates',
        'it' => 'Aggiornamenti',
        'el' => 'Ενημερώσεις',
    ],
    'analytics_page_form' => [
        'fi' => 'SafetyFlash-luontilomake',
        'sv' => 'SafetyFlash skapandeformulär',
        'en' => 'SafetyFlash creation form',
        'it' => 'Modulo di creazione SafetyFlash',
        'el' => 'Φόρμα δημιουργίας SafetyFlash',
    ],
    'analytics_page_form_language' => [
        'fi' => 'SafetyFlash-kieliversion lomake',
        'sv' => 'Formulär för SafetyFlash språkversion',
        'en' => 'SafetyFlash language version form',
        'it' => 'Modulo versione linguistica SafetyFlash',
        'el' => 'Φόρμα γλωσσικής έκδοσης SafetyFlash',
    ],
    'analytics_page_profile' => [
        'fi' => 'Profiili',
        'sv' => 'Profil',
        'en' => 'Profile',
        'it' => 'Profilo',
        'el' => 'Προφίλ',
    ],
    'analytics_page_playlist_manager' => [
        'fi' => 'Näyttöjen hallinta',
        'sv' => 'Skärmhantering',
        'en' => 'Display management',
        'it' => 'Gestione display',
        'el' => 'Διαχείριση οθονών',
    ],
    'analytics_page_users' => [
        'fi' => 'Käyttäjähallinta',
        'sv' => 'Användarhantering',
        'en' => 'User management',
        'it' => 'Gestione utenti',
        'el' => 'Διαχείριση χρηστών',
    ],
    'analytics_source_push' => [
        'fi' => 'Push-ilmoitus',
        'sv' => 'Pushnotis',
        'en' => 'Push notification',
        'it' => 'Notifica push',
        'el' => 'Push ειδοποίηση',
    ],
    'analytics_source_list' => [
        'fi' => 'SafetyFlash-lista',
        'sv' => 'SafetyFlash-lista',
        'en' => 'SafetyFlash list',
        'it' => 'Elenco SafetyFlash',
        'el' => 'Λίστα SafetyFlash',
    ],
    'analytics_source_list_thumb' => [
        'fi' => 'Listan kuvakortti',
        'sv' => 'Bildkort i listan',
        'en' => 'List image card',
        'it' => 'Scheda immagine elenco',
        'el' => 'Κάρτα εικόνας λίστας',
    ],
    'analytics_source_list_button' => [
        'fi' => 'Listan avaa-painike',
        'sv' => 'Öppna-knapp i listan',
        'en' => 'List open button',
        'it' => 'Pulsante apri elenco',
        'el' => 'Κουμπί ανοίγματος λίστας',
    ],
    'analytics_source_dashboard' => [
        'fi' => 'Dashboard',
        'sv' => 'Dashboard',
        'en' => 'Dashboard',
        'it' => 'Dashboard',
        'el' => 'Dashboard',
    ],
    'analytics_source_dashboard_waiting' => [
        'fi' => 'Dashboardin odottavat tehtävät',
        'sv' => 'Väntande uppgifter på dashboarden',
        'en' => 'Dashboard pending tasks',
        'it' => 'Attività in sospeso dashboard',
        'el' => 'Εκκρεμείς εργασίες dashboard',
    ],
    'analytics_source_dashboard_latest' => [
        'fi' => 'Dashboardin viimeisimmät',
        'sv' => 'Senaste på dashboarden',
        'en' => 'Dashboard latest',
        'it' => 'Ultimi nel dashboard',
        'el' => 'Τελευταία στο dashboard',
    ],
    'analytics_source_dashboard_injury' => [
        'fi' => 'Dashboardin tapaturmanäkymä',
        'sv' => 'Skadevy på dashboarden',
        'en' => 'Dashboard injury view',
        'it' => 'Vista infortuni dashboard',
        'el' => 'Προβολή τραυματισμών dashboard',
    ],
    'analytics_source_dashboard_monthly' => [
        'fi' => 'Dashboardin kuukausivalinta',
        'sv' => 'Månadsval på dashboarden',
        'en' => 'Dashboard monthly selection',
        'it' => 'Selezione mensile dashboard',
        'el' => 'Μηνιαία επιλογή dashboard',
    ],
    'analytics_source_direct' => [
        'fi' => 'Suora avaus',
        'sv' => 'Direkt öppning',
        'en' => 'Direct open',
        'it' => 'Apertura diretta',
        'el' => 'Άμεσο άνοιγμα',
    ],
    'analytics_source_external' => [
        'fi' => 'Ulkoinen viittaus',
        'sv' => 'Extern hänvisning',
        'en' => 'External referrer',
        'it' => 'Riferimento esterno',
        'el' => 'Εξωτερική παραπομπή',
    ],
    'analytics_source_referrer' => [
        'fi' => 'Viittaava sivu',
        'sv' => 'Hänvisande sida',
        'en' => 'Referring page',
        'it' => 'Pagina di riferimento',
        'el' => 'Σελίδα παραπομπής',
    ],
	    'analytics_period_year' => [
        'fi' => 'Koko vuosi',
        'sv' => 'Hela året',
        'en' => 'Full year',
        'it' => 'Intero anno',
        'el' => 'Ολόκληρο έτος',
    ],
    'analytics_period_month' => [
        'fi' => 'Kuukausi',
        'sv' => 'Månad',
        'en' => 'Month',
        'it' => 'Mese',
        'el' => 'Μήνας',
    ],
    'analytics_select_year' => [
        'fi' => 'Valitse vuosi',
        'sv' => 'Välj år',
        'en' => 'Select year',
        'it' => 'Seleziona anno',
        'el' => 'Επιλέξτε έτος',
    ],
    'analytics_select_month' => [
        'fi' => 'Valitse kuukausi',
        'sv' => 'Välj månad',
        'en' => 'Select month',
        'it' => 'Seleziona mese',
        'el' => 'Επιλέξτε μήνα',
    ],
    'analytics_all_months' => [
        'fi' => 'Kaikki kuukaudet',
        'sv' => 'Alla månader',
        'en' => 'All months',
        'it' => 'Tutti i mesi',
        'el' => 'Όλοι οι μήνες',
    ],
    'analytics_loading_hint' => [
        'fi' => 'Haetaan käyttäjä-, PWA-, sivu- ja SafetyFlash-tilastoja valitulta ajanjaksolta.',
        'sv' => 'Hämtar användar-, PWA-, sid- och SafetyFlash-statistik för vald period.',
        'en' => 'Loading user, PWA, page and SafetyFlash statistics for the selected period.',
        'it' => 'Caricamento statistiche utenti, PWA, pagine e SafetyFlash per il periodo selezionato.',
        'el' => 'Φόρτωση στατιστικών χρηστών, PWA, σελίδων και SafetyFlash για την επιλεγμένη περίοδο.',
    ],
	'month_january' => [
    'fi' => 'Tammikuu',
    'sv' => 'Januari',
    'en' => 'January',
    'it' => 'Gennaio',
    'el' => 'Ιανουάριος',
],

'month_february' => [
    'fi' => 'Helmikuu',
    'sv' => 'Februari',
    'en' => 'February',
    'it' => 'Febbraio',
    'el' => 'Φεβρουάριος',
],

'month_march' => [
    'fi' => 'Maaliskuu',
    'sv' => 'Mars',
    'en' => 'March',
    'it' => 'Marzo',
    'el' => 'Μάρτιος',
],

'month_april' => [
    'fi' => 'Huhtikuu',
    'sv' => 'April',
    'en' => 'April',
    'it' => 'Aprile',
    'el' => 'Απρίλιος',
],

'month_may' => [
    'fi' => 'Toukokuu',
    'sv' => 'Maj',
    'en' => 'May',
    'it' => 'Maggio',
    'el' => 'Μάιος',
],

'month_june' => [
    'fi' => 'Kesäkuu',
    'sv' => 'Juni',
    'en' => 'June',
    'it' => 'Giugno',
    'el' => 'Ιούνιος',
],

'month_july' => [
    'fi' => 'Heinäkuu',
    'sv' => 'Juli',
    'en' => 'July',
    'it' => 'Luglio',
    'el' => 'Ιούλιος',
],

'month_august' => [
    'fi' => 'Elokuu',
    'sv' => 'Augusti',
    'en' => 'August',
    'it' => 'Agosto',
    'el' => 'Αύγουστος',
],

'month_september' => [
    'fi' => 'Syyskuu',
    'sv' => 'September',
    'en' => 'September',
    'it' => 'Settembre',
    'el' => 'Σεπτέμβριος',
],

'month_october' => [
    'fi' => 'Lokakuu',
    'sv' => 'Oktober',
    'en' => 'October',
    'it' => 'Ottobre',
    'el' => 'Οκτώβριος',
],

'month_november' => [
    'fi' => 'Marraskuu',
    'sv' => 'November',
    'en' => 'November',
    'it' => 'Novembre',
    'el' => 'Νοέμβριος',
],

'month_december' => [
    'fi' => 'Joulukuu',
    'sv' => 'December',
    'en' => 'December',
    'it' => 'Dicembre',
    'el' => 'Δεκέμβριος',
],
	    'analytics_push_notifications' => [
        'fi' => 'Push-ilmoitukset',
        'sv' => 'Pushnotiser',
        'en' => 'Push notifications',
        'it' => 'Notifiche push',
        'el' => 'Push ειδοποιήσεις',
    ],
	    'analytics_push_notifications' => [
        'fi' => 'Push-ilmoitukset',
        'sv' => 'Pushnotiser',
        'en' => 'Push notifications',
        'it' => 'Notifiche push',
        'el' => 'Push ειδοποιήσεις',
    ],
    'analytics_push_notifications_hint' => [
        'fi' => 'Näyttää kuinka monta push-ilmoitusta on lähetetty ja kuinka moni niistä on avattu.',
        'sv' => 'Visar hur många pushnotiser som har skickats och hur många som har öppnats.',
        'en' => 'Shows how many push notifications were sent and how many were opened.',
        'it' => 'Mostra quante notifiche push sono state inviate e quante sono state aperte.',
        'el' => 'Δείχνει πόσες push ειδοποιήσεις στάλθηκαν και πόσες ανοίχθηκαν.',
    ],
	    'analytics_load_error' => [
        'fi' => 'Analytiikan lataus epäonnistui. Päivitä sivu tai kokeile toista ajanjaksoa.',
        'sv' => 'Det gick inte att läsa in analysen. Uppdatera sidan eller prova en annan period.',
        'en' => 'Analytics failed to load. Refresh the page or try another period.',
        'it' => 'Impossibile caricare le analisi. Aggiorna la pagina o prova un altro periodo.',
        'el' => 'Η φόρτωση των αναλυτικών στοιχείων απέτυχε. Ανανεώστε τη σελίδα ή δοκιμάστε άλλη περίοδο.',
    ],
	    'analytics_user_filter' => [
        'fi' => 'Käyttäjäsuodatin',
        'sv' => 'Användarfilter',
        'en' => 'User filter',
        'it' => 'Filtro utenti',
        'el' => 'Φίλτρο χρηστών',
    ],
    'analytics_filter_without_admins' => [
        'fi' => 'Ilman admineja',
        'sv' => 'Utan administratörer',
        'en' => 'Without admins',
        'it' => 'Senza amministratori',
        'el' => 'Χωρίς διαχειριστές',
    ],
    'analytics_filter_all_users' => [
        'fi' => 'Kaikki käyttäjät',
        'sv' => 'Alla användare',
        'en' => 'All users',
        'it' => 'Tutti gli utenti',
        'el' => 'Όλοι οι χρήστες',
    ],
    'analytics_filter_admins_only' => [
        'fi' => 'Vain adminit',
        'sv' => 'Endast administratörer',
        'en' => 'Admins only',
        'it' => 'Solo amministratori',
        'el' => 'Μόνο διαχειριστές',
    ],
	    'analytics_pwa_install_rate' => [
        'fi' => 'PWA-asennusaste',
        'sv' => 'PWA-installationsgrad',
        'en' => 'PWA install rate',
        'it' => 'Tasso installazione PWA',
        'el' => 'Ποσοστό εγκατάστασης PWA',
    ],
    'analytics_push_permission_granted' => [
        'fi' => 'Push sallittu',
        'sv' => 'Push tillåten',
        'en' => 'Push allowed',
        'it' => 'Push consentito',
        'el' => 'Push επιτρέπεται',
    ],
    'analytics_push_permission_denied' => [
        'fi' => 'Push estetty',
        'sv' => 'Push blockerad',
        'en' => 'Push blocked',
        'it' => 'Push bloccato',
        'el' => 'Push αποκλεισμένο',
    ],
    'analytics_push_permission_default' => [
        'fi' => 'Push ei valittu',
        'sv' => 'Push ej valt',
        'en' => 'Push not selected',
        'it' => 'Push non selezionato',
        'el' => 'Push μη επιλεγμένο',
    ],
    'analytics_read_full_rate' => [
        'fi' => 'Luettu loppuun %',
        'sv' => 'Läst till slut %',
        'en' => 'Read fully %',
        'it' => 'Letto fino alla fine %',
        'el' => 'Διαβάστηκε πλήρως %',
    ],
    'analytics_unique_readers' => [
        'fi' => 'Uniikit lukijat',
        'sv' => 'Unika läsare',
        'en' => 'Unique readers',
        'it' => 'Lettori unici',
        'el' => 'Μοναδικοί αναγνώστες',
    ],
	    'analytics_date' => [
        'fi' => 'Päivä',
        'sv' => 'Datum',
        'en' => 'Date',
        'it' => 'Data',
        'el' => 'Ημερομηνία',
    ],
    'analytics_user' => [
        'fi' => 'Käyttäjä',
        'sv' => 'Användare',
        'en' => 'User',
        'it' => 'Utente',
        'el' => 'Χρήστης',
    ],
    'analytics_role' => [
        'fi' => 'Rooli',
        'sv' => 'Roll',
        'en' => 'Role',
        'it' => 'Ruolo',
        'el' => 'Ρόλος',
    ],
    'analytics_active_days' => [
        'fi' => 'Aktiiviset päivät',
        'sv' => 'Aktiva dagar',
        'en' => 'Active days',
        'it' => 'Giorni attivi',
        'el' => 'Ενεργές ημέρες',
    ],
    'analytics_full_reads' => [
        'fi' => 'Luettu loppuun',
        'sv' => 'Läst till slut',
        'en' => 'Full reads',
        'it' => 'Letture complete',
        'el' => 'Πλήρεις αναγνώσεις',
    ],
    'analytics_push_opens' => [
        'fi' => 'Push-avaukset',
        'sv' => 'Pushöppningar',
        'en' => 'Push opens',
        'it' => 'Aperture push',
        'el' => 'Ανοίγματα push',
    ],
    'analytics_last_active' => [
        'fi' => 'Viimeksi aktiivinen',
        'sv' => 'Senast aktiv',
        'en' => 'Last active',
        'it' => 'Ultima attività',
        'el' => 'Τελευταία δραστηριότητα',
    ],
    'analytics_unique_flashes' => [
        'fi' => 'Uniikit SafetyFlashit',
        'sv' => 'Unika SafetyFlash',
        'en' => 'Unique SafetyFlashes',
        'it' => 'SafetyFlash unici',
        'el' => 'Μοναδικά SafetyFlash',
    ],
    'analytics_pwa_used' => [
        'fi' => 'PWA käytössä',
        'sv' => 'PWA använd',
        'en' => 'PWA used',
        'it' => 'PWA utilizzata',
        'el' => 'Χρήση PWA',
    ],
	    'analytics_period_day' => [
        'fi' => 'Tänään',
        'sv' => 'Idag',
        'en' => 'Today',
        'it' => 'Oggi',
        'el' => 'Σήμερα',
    ],
    'analytics_select_date' => [
        'fi' => 'Päivämäärä',
        'sv' => 'Datum',
        'en' => 'Date',
        'it' => 'Data',
        'el' => 'Ημερομηνία',
    ],
	    'analytics_internal_clicks' => [
        'fi' => 'Sisäiset klikkaukset',
        'sv' => 'Interna klick',
        'en' => 'Internal clicks',
        'it' => 'Clic interni',
        'el' => 'Εσωτερικά κλικ',
    ],
    'analytics_internal_clicks_hint' => [
        'fi' => 'Näyttää, mitä painikkeita ja välilehtiä käyttäjät avaavat SafetyFlashien ja dashboardin sisällä.',
        'sv' => 'Visar vilka knappar och flikar användarna öppnar inne i SafetyFlash och dashboarden.',
        'en' => 'Shows which buttons and tabs users open inside SafetyFlashes and the dashboard.',
        'it' => 'Mostra quali pulsanti e schede gli utenti aprono all’interno dei SafetyFlash e della dashboard.',
        'el' => 'Δείχνει ποια κουμπιά και καρτέλες ανοίγουν οι χρήστες μέσα στα SafetyFlash και στον πίνακα ελέγχου.',
    ],
    'analytics_internal_click_users' => [
        'fi' => 'Klikkaukset käyttäjittäin',
        'sv' => 'Klick per användare',
        'en' => 'Clicks by user',
        'it' => 'Clic per utente',
        'el' => 'Κλικ ανά χρήστη',
    ],
    'analytics_clicks' => [
        'fi' => 'Klikkaukset',
        'sv' => 'Klick',
        'en' => 'Clicks',
        'it' => 'Clic',
        'el' => 'Κλικ',
    ],
    'analytics_last_click' => [
        'fi' => 'Viimeisin klikkaus',
        'sv' => 'Senaste klick',
        'en' => 'Last click',
        'it' => 'Ultimo clic',
        'el' => 'Τελευταίο κλικ',
    ],
    'analytics_action' => [
        'fi' => 'Toiminto',
        'sv' => 'Åtgärd',
        'en' => 'Action',
        'it' => 'Azione',
        'el' => 'Ενέργεια',
    ],
    'analytics_copy_events' => [
        'fi' => 'Kuvien kopioinnit',
        'sv' => 'Bildkopieringar',
        'en' => 'Image copies',
        'it' => 'Copie delle immagini',
        'el' => 'Αντιγραφές εικόνων',
    ],
];