<?php
/**
 * Navigation and UI Structure - Navigation menus, view states
 */
return [
'nav_settings' => [
    'fi' => 'Asetukset',
    'sv' => 'Inställningar',
    'en' => 'Settings',
    'it' => 'Impostazioni',
    'el' => 'Ρυθμίσεις',
],
'view_status' => [
    'fi' => 'Tila',
    'sv' => 'Status',
    'en' => 'Status',
    'it' => 'Stato',
    'el' => 'Κατάσταση',
],
'view_details_heading' => [
    'fi' => 'Safetyflash-tiedot',
    'sv' => 'Information om Safetyflash',
    'en' => 'Safetyflash details',
    'it' => 'Dettagli Safetyflash',
    'el' => 'Λεπτομέρειες Safetyflash',
],
'view_languages_aria' => [
    'fi' => 'Kielet',
    'sv' => 'Språk',
    'en' => 'Languages',
    'it' => 'Lingue',
    'el' => 'Γλώσσες',
],
'nav_list' => [
    'fi' => 'Lista',
    'sv' => 'Lista',
    'en' => 'List',
    'it' => 'Lista',
    'el' => 'Λίστα',
],
'nav_new_safetyflash' => [
    'fi' => 'Uusi Safetyflash',
    'sv' => 'Ny Safetyflash',
    'en' => 'New Safetyflash',
    'it' => 'Nuovo Safetyflash',
    'el' => 'Νέο Safetyflash',
],
'nav_profile' => [
    'fi' => 'Profiili',
    'sv' => 'Profil',
    'en' => 'Profile',
    'it' => 'Profilo',
    'el' => 'Προφίλ',
],
'nav_logout' => [
    'fi' => 'Kirjaudu ulos',
    'sv' => 'Logga ut',
    'en' => 'Log out',
    'it' => 'Esci',
    'el' => 'Αποσύνδεση',
],
'view_grid' => [
    'fi' => 'Ruudukko',
    'sv' => 'Rutnät',
    'en' => 'Grid',
    'it' => 'Griglia',
    'el' => 'Πλέγμα',
],
'view_list' => [
    'fi' => 'Lista',
    'sv' => 'Lista',
    'en' => 'List',
    'it' => 'Elenco',
    'el' => 'Λίστα',
],
'view_compact' => [
    'fi' => 'Tiivis',
    'sv' => 'Kompakt',
    'en' => 'Compact',
    'it' => 'Compatto',
    'el' => 'Συμπαγής',
],
'view_toggle' => [
    'fi' => 'Vaihda näkymää',
    'sv' => 'Byt vy',
    'en' => 'Toggle view',
    'it' => 'Cambia visualizzazione',
    'el' => 'Εναλλαγή προβολής',
],
'nav_feedback' => [
    'fi' => 'Palaute',
    'sv' => 'Feedback',
    'en' => 'Feedback',
    'it' => 'Feedback',
    'el' => 'Ανατροφοδότηση',
],
'nav_language_select' => [
    'fi' => 'Valitse kieli',
    'sv' => 'Välj språk',
    'en' => 'Select language',
    'it' => 'Seleziona lingua',
    'el' => 'Επιλέξτε γλώσσα',
],
'form_language_label' => [
    'fi' => 'Kieliversio',
    'sv' => 'Språkversion',
    'en' => 'Language version',
    'it' => 'Versione linguistica',
    'el' => 'Γλωσσική έκδοση',
],
'nav_display_playlists' => [
    'fi' => 'Infonäytöt',
    'sv' => 'Infoskärmar',
    'en' => 'Info Displays',
    'it' => 'Schermi info',
    'el' => 'Οθόνες πληροφοριών',
],
'nav_admin' => [
    'fi' => 'Ylläpito',
    'sv' => 'Administration',
    'en' => 'Admin',
    'it' => 'Amministrazione',
    'el' => 'Διαχείριση',
],
	'events_heading' => [
    'fi' => 'Tapahtumat',
    'sv' => 'Händelser',
    'en' => 'Events',
    'it' => 'Eventi',
    'el' => 'Συμβάντα',
],
'events_empty' => [
    'fi' => 'Ei uusia tapahtumia',
    'sv' => 'Inga nya händelser',
    'en' => 'No new events',
    'it' => 'Nessun nuovo evento',
    'el' => 'Δεν υπάρχουν νέα συμβάντα',
],
'events_actions_heading' => [
    'fi' => 'Toimenpiteet',
    'sv' => 'Åtgärder',
    'en' => 'Actions',
    'it' => 'Azioni',
    'el' => 'Ενέργειες',
],
'events_info_heading' => [
    'fi' => 'Uudet tapahtumat',
    'sv' => 'Nya händelser',
    'en' => 'New events',
    'it' => 'Nuovi eventi',
    'el' => 'Νέα συμβάντα',
],
'events_comment_added' => [
    'fi' => 'Uusi kommentti',
    'sv' => 'Ny kommentar',
    'en' => 'New comment',
    'it' => 'Nuovo commento',
    'el' => 'Νέο σχόλιο',
],
'events_pending_supervisor' => [
    'fi' => 'Odottaa tarkastustasi',
    'sv' => 'Väntar på din granskning',
    'en' => 'Waiting for your review',
    'it' => 'In attesa della tua revisione',
    'el' => 'Αναμένει τον έλεγχό σας',
],
'events_returned_to_creator' => [
    'fi' => 'Palautettu sinulle',
    'sv' => 'Returnerad till dig',
    'en' => 'Returned to you',
    'it' => 'Restituito a te',
    'el' => 'Επιστράφηκε σε εσάς',
],
'events_sent_to_safety_team' => [
    'fi' => 'Lähetetty turvatiimille',
    'sv' => 'Skickad till säkerhetsteamet',
    'en' => 'Sent to safety team',
    'it' => 'Inviato al team sicurezza',
    'el' => 'Στάλθηκε στην ομάδα ασφάλειας',
],
'events_sent_to_comms' => [
    'fi' => 'Lähetetty viestinnälle',
    'sv' => 'Skickad till kommunikation',
    'en' => 'Sent to communications',
    'it' => 'Inviato alla comunicazione',
    'el' => 'Στάλθηκε στην επικοινωνία',
],
'events_investigation_pending' => [
    'fi' => 'Tutkintatiedote odottaa käsittelyä',
    'sv' => 'Utredningsrapport väntar på behandling',
    'en' => 'Investigation report is waiting for handling',
    'it' => 'Il rapporto di indagine attende la gestione',
    'el' => 'Η αναφορά διερεύνησης αναμένει χειρισμό',
],
'events_language_review_requested' => [
    'fi' => 'Kieliversion tarkastuspyyntö',
    'sv' => 'Begäran om språkgranskning',
    'en' => 'Language review request',
    'it' => 'Richiesta di revisione linguistica',
    'el' => 'Αίτημα γλωσσικού ελέγχου',
],
'events_flash_published' => [
    'fi' => 'SafetyFlash julkaistu',
    'sv' => 'SafetyFlash publicerad',
    'en' => 'SafetyFlash published',
    'it' => 'SafetyFlash pubblicato',
    'el' => 'Το SafetyFlash δημοσιεύτηκε',
],
	'events_mark_all_read' => [
    'fi' => 'Merkitse kaikki luetuiksi',
    'sv' => 'Markera alla som lästa',
    'en' => 'Mark all as read',
    'it' => 'Segna tutti come letti',
    'el' => 'Σήμανση όλων ως αναγνωσμένων',
],
	'events_mark_all_short' => [
    'fi' => 'Kaikki',
    'sv' => 'Alla',
    'en' => 'All',
    'it' => 'Tutti',
    'el' => 'Όλα',
],
];