<?php
/**
 * View Page - Flash detail view, metadata, previews, cards
 */
return [
'card_1_summary' => [
    'fi' => '1. Yhteenveto & kuvat',
    'sv' => '1. Sammanfattning & bilder',
    'en' => '1. Summary & images',
    'it' => '1. Riepilogo & immagini',
    'el' => '1. Σύνοψη & εικόνες',
],
'card_2_investigation' => [
    'fi' => '2. Juurisyyt & toimenpiteet',
    'sv' => '2. Grundorsaker & åtgärder',
    'en' => '2. Root causes & actions',
    'it' => '2. Cause & azioni',
    'el' => '2. Αιτίες & ενέργειες',
],
'card_1' => [
    'fi' => 'Kortti 1',
    'sv' => 'Kort 1',
    'en' => 'Card 1',
    'it' => 'Scheda 1',
    'el' => 'Κάρτα 1',
],
'card_2' => [
    'fi' => 'Kortti 2',
    'sv' => 'Kort 2',
    'en' => 'Card 2',
    'it' => 'Scheda 2',
    'el' => 'Κάρτα 2',
],
	'footer_display_targets' => [
    'fi' => 'Infonäytöt',
    'sv' => 'Infoskärmar',
    'en' => 'Displays',
    'it' => 'Schermi',
    'el' => 'Οθόνες',
],
	'publish_original_description' => [
    'fi' => 'Julkaise SafetyFlash infonäytöille ja valituille jakelukanaville.',
    'sv' => 'Publicera SafetyFlash på informationsskärmar och valda distributionskanaler.',
    'en' => 'Publish the SafetyFlash to displays and selected distribution channels.',
    'it' => 'Pubblica il SafetyFlash sugli schermi informativi e sui canali di distribuzione selezionati.',
    'el' => 'Δημοσιεύστε το SafetyFlash στις οθόνες πληροφοριών και στα επιλεγμένα κανάλια διανομής.',
],
'athena_saved_status' => [
    'fi' => 'Tallennettu Athenaan',
    'sv' => 'Sparad i Athena',
    'en' => 'Saved to Athena',
    'it' => 'Salvato su Athena',
    'el' => 'Αποθηκεύτηκε στο Athena',
],
'preview_2_not_generated' => [
    'fi' => 'Kortin 2 esikatselukuvaa ei ole vielä generoitu.',
    'sv' => 'Kort 2:s förhandsvisning har inte genererats ännu.',
    'en' => 'Card 2 preview has not been generated yet.',
    'it' => 'L\'anteprima della scheda 2 non è ancora stata generata.',
    'el' => 'Η προεπισκόπηση της κάρτας 2 δεν έχει δημιουργηθεί ακόμα.',
],
'card_modified' => [
    'fi' => 'viimeksi muokattu',
    'sv' => 'senast ändrad',
    'en' => 'last modified',
    'it' => 'ultima modifica',
    'el' => 'τελευταία τροποποίηση',
],
'card_open' => [
    'fi' => 'Avaa',
    'sv' => 'Öppna',
    'en' => 'Open',
    'it' => 'Apri',
    'el' => 'Άνοιγμα',
],
'meta_title_internal' => [
    'fi' => 'Otsikko (vain järjestelmää varten)',
    'sv' => 'Rubrik (endast för systemet)',
    'en' => 'Title (system only)',
    'it' => 'Titolo (solo per il sistema)',
    'el' => 'Τίτλος (μόνο για το σύστημα)',
],
'meta_summary_short' => [
    'fi' => 'Lyhyt yhteenveto',
    'sv' => 'Kort sammanfattning',
    'en' => 'Short summary',
    'it' => 'Breve sommario',
    'el' => 'Σύντομη σύνοψη',
],
'meta_description_long' => [
    'fi' => 'Pitkä kuvaus',
    'sv' => 'Lång beskrivning',
    'en' => 'Long description',
    'it' => 'Descrizione estesa',
    'el' => 'Εκτενής περιγραφή',
],
'meta_type' => [
    'fi' => 'Tyyppi',
    'sv' => 'Typ',
    'en' => 'Type',
    'it' => 'Tipo',
    'el' => 'Τύπος',
],
'type' => [
    'fi' => 'Tyyppi',
    'sv' => 'Typ',
    'en' => 'Type',
    'it' => 'Tipo',
    'el' => 'Τύπος',
],
'meta_site' => [
    'fi' => 'Työmaa',
    'sv' => 'Arbetsplats',
    'en' => 'Worksite',
    'it' => 'Cantiere',
    'el' => 'Εργοτάξιο',
],
'meta_occurred_at' => [
    'fi' => 'Tapahtuma-aika',
    'sv' => 'Tidpunkt',
    'en' => 'Time of incident',
    'it' => 'Data/ora evento',
    'el' => 'Χρόνος συμβάντος',
],
'meta_system_heading' => [
    'fi' => 'Järjestelmätiedot',
    'sv' => 'Systeminformation',
    'en' => 'System information',
    'it' => 'Informazioni di sistema',
    'el' => 'Πληροφορίες συστήματος',
],
'meta_language' => [
    'fi' => 'Kieli',
    'sv' => 'Språk',
    'en' => 'Language',
    'it' => 'Lingua',
    'el' => 'Γλώσσα',
],
'meta_created_at' => [
    'fi' => 'Luotu',
    'sv' => 'Skapad',
    'en' => 'Created',
    'it' => 'Creato',
    'el' => 'Δημιουργήθηκε',
],
'meta_updated_at' => [
    'fi' => 'Viimeksi muokattu',
    'sv' => 'Senast ändrad',
    'en' => 'Last modified',
    'it' => 'Ultima modifica',
    'el' => 'Τροποποιήθηκε τελευταία',
],
'view_plain_content_title' => [
    'fi' => 'Tekstiversio',
    'sv' => 'Textversion',
    'en' => 'Text version',
    'it' => 'Versione testo',
    'el' => 'Έκδοση κειμένου',
],
'view_plain_title_label' => [
    'fi' => 'Otsikko',
    'sv' => 'Rubrik',
    'en' => 'Title',
    'it' => 'Titolo',
    'el' => 'Τίτλος',
],
'view_plain_copy_btn' => [
    'fi' => 'Kopioi tekstit',
    'sv' => 'Kopiera texter',
    'en' => 'Copy text',
    'it' => 'Copia testi',
    'el' => 'Αντιγραφή κειμένων',
],
'view_plain_copy_success' => [
    'fi' => 'Tekstit kopioitu',
    'sv' => 'Texterna kopierades',
    'en' => 'Text copied',
    'it' => 'Testi copiati',
    'el' => 'Τα κείμενα αντιγράφηκαν',
],
'view_plain_empty' => [
    'fi' => 'Ei tekstisisältöä',
    'sv' => 'Inget textinnehåll',
    'en' => 'No text content',
    'it' => 'Nessun contenuto testuale',
    'el' => 'Δεν υπάρχει περιεχόμενο κειμένου',
],
'preview_and_save' => [
    'fi' => 'Esikatselu ja tallennus',
    'sv' => 'Förhandsgranska och spara',
    'en' => 'Preview and save',
    'it' => 'Anteprima e salva',
    'el' => 'Προεπισκόπηση και αποθήκευση',
],
'preview_type_red' => [
    'fi' => 'ENSITIEDOTE',
    'sv' => 'FÖRSTA UNDERRÄTTELSE',
    'en' => 'FIRST RELEASE',
    'it' => 'PRIMO RILASCIO',
    'el' => 'ΠΡΩΤΗ ΔΗΜΟΣΙΕΥΣΗ',
],
'preview_type_yellow' => [
    'fi' => 'VAARATILANNE',
    'sv' => 'FARLIG SITUATION',
    'en' => 'DANGEROUS SITUATION',
    'it' => 'SITUAZIONE PERICOLOSA',
    'el' => 'ΕΠΙΚΙΝΔΥΝΗ ΚΑΤΑΣΤΑΣΗ',
],
'preview_type_green' => [
    'fi' => 'TUTKINTATIEDOTE',
    'sv' => 'UTREDNINGSRAPPORT',
    'en' => 'INVESTIGATION REPORT',
    'it' => 'RILASCIO DOPO L\'INDAGINE',
    'el' => 'ΕΚΘΕΣΗ ΕΡΕΥΝΑΣ',
],
'preview_brand' => [
    'fi' => 'TAPOJÄRVI SAFETY',
    'sv' => 'TAPOJÄRVI SAFETY',
    'en' => 'TAPOJÄRVI SAFETY',
    'it' => 'TAPOJÄRVI SAFETY',
    'el' => 'TAPOJÄRVI SAFETY',
],
'preview_text_continues' => [
    'fi' => '...[tekstiä jatkuu]',
    'sv' => '...[texten fortsätter]',
    'en' => '...[text continues]',
    'it' => '...[il testo continua]',
    'el' => '...[το κείμενο συνεχίζεται]',
],
'preview_meta_site' => [
    'fi' => 'TYÖMAA:',
    'sv' => 'ARBETSPLATS:',
    'en' => 'WORKSITE:',
    'it' => 'CANTIERE:',
    'el' => 'ΕΡΓΟΤΆΞΙΟ:',
],
'preview_meta_date' => [
    'fi' => 'MILLOIN?',
    'sv' => 'NÄR?',
    'en' => 'WHEN?',
    'it' => 'QUANDO?',
    'el' => 'ΠΌΤΕ;',
],
'display_targets_priority_group' => [
    'fi' => 'Aina näkyvät näyttökohteet',
    'sv' => 'Alltid synliga skärmval',
    'en' => 'Always visible display targets',
    'it' => 'Destinazioni schermo sempre visibili',
    'el' => 'Πάντα ορατοί στόχοι οθόνης',
],
'display_targets_display_only_chip' => [
    'fi' => 'Vain infonäytöissä',
    'sv' => 'Endast informationsskärmar',
    'en' => 'Display-only',
    'it' => 'Solo schermi informativi',
    'el' => 'Μόνο οθόνες ενημέρωσης',
],
'display_targets_uncategorized_chip' => [
    'fi' => 'Kategorisoimattomat',
    'sv' => 'Okategoriserade',
    'en' => 'Uncategorized',
    'it' => 'Non categorizzati',
    'el' => 'Μη κατηγοριοποιημένα',
],
'display_targets_default_chip' => [
    'fi' => 'Oletuksena valitut',
    'sv' => 'Förvalda',
    'en' => 'Default selected',
    'it' => 'Selezionati per default',
    'el' => 'Προεπιλεγμένα',
],
'activity_tab_versions' => [
    'fi' => 'Versiot',
    'sv' => 'Versioner',
    'en' => 'Versions',
    'it' => 'Versioni',
    'el' => 'Εκδόσεις',
],
'version_ensitiedote' => [
    'fi' => 'Ensitiedote',
    'sv' => 'Första underrättelse',
    'en' => 'First release',
    'it' => 'Prima notifica',
    'el' => 'Πρώτη ειδοποίηση',
],
'version_tutkintatiedote' => [
    'fi' => 'Tutkintatiedote',
    'sv' => 'Utredningsmeddelande',
    'en' => 'Investigation report',
    'it' => 'Rapporto di indagine',
    'el' => 'Έκθεση έρευνας',
],
'version_vaaratilanne' => [
    'fi' => 'Vaaratilanne',
    'sv' => 'Farlig situation',
    'en' => 'Dangerous situation',
    'it' => 'Situazione pericolosa',
    'el' => 'Επικίνδυνη κατάσταση',
],
'version_paivitys' => [
    'fi' => 'Päivitys',
    'sv' => 'Uppdatering',
    'en' => 'Update',
    'it' => 'Aggiornamento',
    'el' => 'Ενημέρωση',
],
'version_published' => [
    'fi' => 'Julkaistu',
    'sv' => 'Publicerad',
    'en' => 'Published',
    'it' => 'Pubblicato',
    'el' => 'Δημοσιεύτηκε',
],
'version_view' => [
    'fi' => 'Näytä',
    'sv' => 'Visa',
    'en' => 'View',
    'it' => 'Visualizza',
    'el' => 'Προβολή',
],
'version_download' => [
    'fi' => 'Lataa JPG',
    'sv' => 'Ladda ner JPG',
    'en' => 'Download JPG',
    'it' => 'Scarica JPG',
    'el' => 'Λήψη JPG',
],
'version_no_versions' => [
    'fi' => 'Ei julkaistuja versioita',
    'sv' => 'Inga publicerade versioner',
    'en' => 'No published versions',
    'it' => 'Nessuna versione pubblicata',
    'el' => 'Δεν υπάρχουν δημοσιευμένες εκδόσεις',
],
'version_current' => [
    'fi' => 'Nykyinen',
    'sv' => 'Aktuell', 
    'en' => 'Current',
    'it' => 'Attuale',
    'el' => 'Τρέχουσα',
],
'version_number' => [
    'fi' => 'Versio',
    'sv' => 'Version',
    'en' => 'Version',
    'it' => 'Versione',
    'el' => 'Έκδοση',
],
'log_delete' => [
    'fi' => 'Poista',
    'sv' => 'Radera',
    'en' => 'Delete',
    'it' => 'Elimina',
    'el' => 'Διαγραφή',
],
'log_delete_alt' => [
    'fi' => 'Poista lokimerkintä',
    'sv' => 'Radera loggpost',
    'en' => 'Delete log entry',
    'it' => 'Elimina voce di registro',
    'el' => 'Διαγραφή καταχώρησης',
],
'log_delete_title' => [
    'fi' => 'Poista lokimerkintä',
    'sv' => 'Radera loggpost',
    'en' => 'Delete log entry',
    'it' => 'Elimina voce di registro',
    'el' => 'Διαγραφή καταχώρησης',
],
'log_delete_confirm' => [
    'fi' => 'Haluatko varmasti poistaa tämän lokimerkinnän? Tätä toimintoa ei voi peruuttaa.',
    'sv' => 'Är du säker på att du vill radera denna loggpost? Denna åtgärd kan inte ångras.',
    'en' => 'Are you sure you want to delete this log entry? This action cannot be undone.',
    'it' => 'Sei sicuro di voler eliminare questa voce di registro? Questa azione non può essere annullata.',
    'el' => 'Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτήν την καταχώρηση; Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.',
],
'log_deleted' => [
    'fi' => 'Lokimerkintä poistettu',
    'sv' => 'Loggpost raderad',
    'en' => 'Log entry deleted',
    'it' => 'Voce di registro eliminata',
    'el' => 'Η καταχώρηση διαγράφηκε',
],
'log_delete_error' => [
    'fi' => 'Virhe lokimerkinnän poistamisessa',
    'sv' => 'Fel vid radering av loggpost',
    'en' => 'Error deleting log entry',
    'it' => 'Errore nell\'eliminazione della voce di registro',
    'el' => 'Σφάλμα κατά τη διαγραφή καταχώρησης',
],
'reviewer_section_title' => [
    'fi' => 'Tarkistaja',
    'sv' => 'Granskare',
    'en' => 'Reviewer',
    'it' => 'Revisore',
    'el' => 'Ελεγκτής',
],
'add_reviewer' => [
    'fi' => 'Lisää tarkistaja',
    'sv' => 'Lägg till granskare',
    'en' => 'Add reviewer',
    'it' => 'Aggiungi revisore',
    'el' => 'Προσθήκη ελεγκτή',
],
'replace_reviewer' => [
    'fi' => 'Vaihda tarkistaja',
    'sv' => 'Byt granskare',
    'en' => 'Replace reviewer',
    'it' => 'Sostituisci revisore',
    'el' => 'Αντικατάσταση ελεγκτή',
],
'remove_reviewer' => [
    'fi' => 'Poista tarkistaja',
    'sv' => 'Ta bort granskare',
    'en' => 'Remove reviewer',
    'it' => 'Rimuovi revisore',
    'el' => 'Κατάργηση ελεγκτή',
],
'reviewer_search_placeholder' => [
    'fi' => '🔍 Hae käyttäjiä...',
    'sv' => '🔍 Sök användare...',
    'en' => '🔍 Search users...',
    'it' => '🔍 Cerca utenti...',
    'el' => '🔍 Αναζήτηση χρηστών...',
],
'reviewer_add_modal_title' => [
    'fi' => 'Lisää tarkistaja',
    'sv' => 'Lägg till granskare',
    'en' => 'Add reviewer',
    'it' => 'Aggiungi revisore',
    'el' => 'Προσθήκη ελεγκτή',
],
'reviewer_replace_modal_title' => [
    'fi' => 'Vaihda tarkistaja',
    'sv' => 'Byt granskare',
    'en' => 'Replace reviewer',
    'it' => 'Sostituisci revisore',
    'el' => 'Αντικατάσταση ελεγκτή',
],
'reviewer_current_reviewers' => [
    'fi' => 'Nykyiset tarkistajat:',
    'sv' => 'Nuvarande granskare:',
    'en' => 'Current reviewers:',
    'it' => 'Revisori attuali:',
    'el' => 'Τρέχοντες ελεγκτές:',
],
'reviewer_no_reviewers' => [
    'fi' => 'Ei tarkistajia',
    'sv' => 'Inga granskare',
    'en' => 'No reviewers',
    'it' => 'Nessun revisore',
    'el' => 'Δεν υπάρχουν ελεγκτές',
],
'reviewer_select_user' => [
    'fi' => 'Valitse käyttäjä',
    'sv' => 'Välj användare',
    'en' => 'Select user',
    'it' => 'Seleziona utente',
    'el' => 'Επιλογή χρήστη',
],
'reviewer_remove_confirm' => [
    'fi' => 'Haluatko varmasti poistaa tämän tarkistajan?',
    'sv' => 'Är du säker på att du vill ta bort denna granskare?',
    'en' => 'Are you sure you want to remove this reviewer?',
    'it' => 'Sei sicuro di voler rimuovere questo revisore?',
    'el' => 'Είστε βέβαιοι ότι θέλετε να καταργήσετε αυτόν τον ελεγκτή;',
],
'reviewer_added' => [
    'fi' => 'Tarkistaja lisätty',
    'sv' => 'Granskare tillagd',
    'en' => 'Reviewer added',
    'it' => 'Revisore aggiunto',
    'el' => 'Προστέθηκε ελεγκτής',
],
'reviewer_replaced' => [
    'fi' => 'Tarkistaja vaihdettu',
    'sv' => 'Granskare bytt',
    'en' => 'Reviewer replaced',
    'it' => 'Revisore sostituito',
    'el' => 'Αντικαταστάθηκε ελεγκτής',
],
'reviewer_removed' => [
    'fi' => 'Tarkistaja poistettu',
    'sv' => 'Granskare borttagen',
    'en' => 'Reviewer removed',
    'it' => 'Revisore rimosso',
    'el' => 'Καταργήθηκε ελεγκτής',
],
'reviewer_error' => [
    'fi' => 'Virhe tarkistajan käsittelyssä',
    'sv' => 'Fel vid hantering av granskare',
    'en' => 'Error processing reviewer',
    'it' => 'Errore nel processare il revisore',
    'el' => 'Σφάλμα επεξεργασίας ελεγκτή',
],
'reviewer_assigned_at' => [
    'fi' => 'Lisätty',
    'sv' => 'Tillagd',
    'en' => 'Added',
    'it' => 'Aggiunto',
    'el' => 'Προστέθηκε',
],
'reviewer_no_users_found' => [
    'fi' => 'Ei käyttäjiä löydetty',
    'sv' => 'Inga användare hittades',
    'en' => 'No users found',
    'it' => 'Nessun utente trovato',
    'el' => 'Δεν βρέθηκαν χρήστες',
],
'btn_report' => [
    'fi' => 'Raportti',
    'en' => 'Report',
    'sv' => 'Rapport',
    'it' => 'Rapporto',
    'el' => 'Αναφορά',
],
'report_generating' => [
    'fi' => 'Luodaan raporttia...',
    'sv' => 'Skapar rapport...',
    'en' => 'Generating report...',
    'it' => 'Generazione report...',
    'el' => 'Δημιουργία αναφοράς...',
],
'report_success' => [
    'fi' => 'Raportti ladattu onnistuneesti',
    'sv' => 'Rapporten har laddats ner',
    'en' => 'Report downloaded successfully',
    'it' => 'Report scaricato con successo',
    'el' => 'Η αναφορά λήφθηκε επιτυχώς',
],
'report_error' => [
    'fi' => 'Raportin generointi epäonnistui',
    'sv' => 'Rapporten kunde inte genereras',
    'en' => 'Report generation failed',
    'it' => 'Generazione report fallita',
    'el' => 'Η δημιουργία αναφοράς απέτυχε',
],
'report_button_loading' => [
    'fi' => 'Luodaan...',
    'sv' => 'Skapar...',
    'en' => 'Generating...',
    'it' => 'Creazione...',
    'el' => 'Δημιουργία...',
],
'report_button_done' => [
    'fi' => 'Valmis!',
    'sv' => 'Klar!',
    'en' => 'Done!',
    'it' => 'Fatto!',
    'el' => 'Έτοιμο!',
],
'report_button_error' => [
    'fi' => 'Virhe!',
    'sv' => 'Fel!',
    'en' => 'Error!',
    'it' => 'Errore!',
    'el' => 'Σφάλμα!',
],
'lang_add_button_text' => [
    'fi' => '+Lisää',
    'sv' => '+Lägg till',
    'en' => '+Add',
    'it' => '+Aggiungi',
    'el' => '+Προσθήκη',
],
'lang_tooltip_active_fi' => [
    'fi' => 'Suomi (aktiivinen)',
    'sv' => 'Finska (aktiv)',
    'en' => 'Finnish (active)',
    'it' => 'Finlandese (attivo)',
    'el' => 'Φινλανδικά (ενεργό)',
],
'lang_tooltip_active_sv' => [
    'fi' => 'Ruotsi (aktiivinen)',
    'sv' => 'Svenska (aktiv)',
    'en' => 'Swedish (active)',
    'it' => 'Svedese (attivo)',
    'el' => 'Σουηδικά (ενεργό)',
],
'lang_tooltip_active_en' => [
    'fi' => 'Englanti (aktiivinen)',
    'sv' => 'Engelska (aktiv)',
    'en' => 'English (active)',
    'it' => 'Inglese (attivo)',
    'el' => 'Αγγλικά (ενεργό)',
],
'lang_tooltip_active_it' => [
    'fi' => 'Italia (aktiivinen)',
    'sv' => 'Italienska (aktiv)',
    'en' => 'Italian (active)',
    'it' => 'Italiano (attivo)',
    'el' => 'Ιταλικά (ενεργό)',
],
'lang_tooltip_active_el' => [
    'fi' => 'Kreikka (aktiivinen)',
    'sv' => 'Grekiska (aktiv)',
    'en' => 'Greek (active)',
    'it' => 'Greco (attivo)',
    'el' => 'Ελληνικά (ενεργό)',
],
'lang_tooltip_goto_fi' => [
    'fi' => 'Suomi – Siirry versioon',
    'sv' => 'Finska – Gå till version',
    'en' => 'Finnish – Go to version',
    'it' => 'Finlandese – Vai alla versione',
    'el' => 'Φινλανδικά – Μετάβαση στην έκδοση',
],
'lang_tooltip_goto_sv' => [
    'fi' => 'Ruotsi – Siirry versioon',
    'sv' => 'Svenska – Gå till version',
    'en' => 'Swedish – Go to version',
    'it' => 'Svedese – Vai alla versione',
    'el' => 'Σουηδικά – Μετάβαση στην έκδοση',
],
'lang_tooltip_goto_en' => [
    'fi' => 'Englanti – Siirry versioon',
    'sv' => 'Engelska – Gå till version',
    'en' => 'English – Go to version',
    'it' => 'Inglese – Vai alla versione',
    'el' => 'Αγγλικά – Μετάβαση στην έκδοση',
],
'lang_tooltip_goto_it' => [
    'fi' => 'Italia – Siirry versioon',
    'sv' => 'Italienska – Gå till version',
    'en' => 'Italian – Go to version',
    'it' => 'Italiano – Vai alla versione',
    'el' => 'Ιταλικά – Μετάβαση στην έκδοση',
],
'lang_tooltip_goto_el' => [
    'fi' => 'Kreikka – Siirry versioon',
    'sv' => 'Grekiska – Gå till version',
    'en' => 'Greek – Go to version',
    'it' => 'Greco – Vai alla versione',
    'el' => 'Ελληνικά – Μετάβαση στην έκδοση',
],
'lang_tooltip_add_fi' => [
    'fi' => 'Lisää suomenkielinen versio',
    'sv' => 'Lägg till finsk version',
    'en' => 'Add Finnish version',
    'it' => 'Aggiungi versione finlandese',
    'el' => 'Προσθήκη φινλανδικής έκδοσης',
],
'lang_tooltip_add_sv' => [
    'fi' => 'Lisää ruotsinkielinen versio',
    'sv' => 'Lägg till svensk version',
    'en' => 'Add Swedish version',
    'it' => 'Aggiungi versione svedese',
    'el' => 'Προσθήκη σουηδικής έκδοσης',
],
'lang_tooltip_add_en' => [
    'fi' => 'Lisää englanninkielinen versio',
    'sv' => 'Lägg till engelsk version',
    'en' => 'Add English version',
    'it' => 'Aggiungi versione inglese',
    'el' => 'Προσθήκη αγγλικής έκδοσης',
],
'lang_tooltip_add_it' => [
    'fi' => 'Lisää italiankielinen versio',
    'sv' => 'Lägg till italiensk version',
    'en' => 'Add Italian version',
    'it' => 'Aggiungi versione italiana',
    'el' => 'Προσθήκη ιταλικής έκδοσης',
],
'lang_tooltip_add_el' => [
    'fi' => 'Lisää kreikankielinen versio',
    'sv' => 'Lägg till grekisk version',
    'en' => 'Add Greek version',
    'it' => 'Aggiungi versione greca',
    'el' => 'Προσθήκη ελληνικής έκδοσης',
],
'comment_email_subscribe' => [
    'fi' => 'Haluan sähköposti-ilmoitukset tämän SafetyFlashin uusista kommenteista',
    'sv' => 'Jag vill få e-postmeddelanden om nya kommentarer på denna SafetyFlash',
    'en' => 'I want email notifications about new comments on this SafetyFlash',
    'it' => 'Voglio ricevere notifiche via e-mail per i nuovi commenti su questo SafetyFlash',
    'el' => 'Θέλω να λαμβάνω ειδοποιήσεις μέσω email για νέα σχόλια σε αυτό το SafetyFlash'
],
'settings_modal_title' => [
    'fi' => 'Raportin asetukset',
    'sv' => 'Rapportinställningar',
    'en' => 'Report settings',
    'it' => 'Impostazioni del rapporto',
    'el' => 'Ρυθμίσεις αναφοράς',
],
'settings_original_type_label' => [
    'fi' => 'Alkuperäinen tyyppi',
    'sv' => 'Ursprunglig typ',
    'en' => 'Original type',
    'it' => 'Tipo originale',
    'el' => 'Αρχικός τύπος',
],
'settings_original_type_none' => [
    'fi' => '— Ei määritetty —',
    'sv' => '— Inte angiven —',
    'en' => '— Not set —',
    'it' => '— Non impostato —',
    'el' => '— Δεν έχει οριστεί —',
],
'settings_original_type_saved' => [
    'fi' => 'Tallennettu',
    'sv' => 'Sparad',
    'en' => 'Saved',
    'it' => 'Salvato',
    'el' => 'Αποθηκεύτηκε',
],
'settings_original_type_error' => [
    'fi' => 'Tallennus epäonnistui',
    'sv' => 'Fel vid sparning',
    'en' => 'Save failed',
    'it' => 'Salvataggio non riuscito',
    'el' => 'Αποτυχία αποθήκευσης',
],
'body_parts_section_title' => [
    'fi' => 'Kehonosat',
    'sv' => 'Kroppsdelar',
    'en' => 'Body parts',
    'it' => 'Parti del corpo',
    'el' => 'Μέλη του σώματος',
],
'additional_info_tab_label' => [
    'fi' => 'Lisätiedot',
    'sv' => 'Info',
    'en' => 'Info',
    'it' => 'Info',
    'el' => 'Πληρ.',
],
'additional_info_description' => [
    'fi' => 'Tähän voit lisätä tarkentavia tekstejä, jotka eivät mahdu varsinaiseen Safetyflash-kuvaan. Nämä tiedot tulostuvat automaattisesti PDF-raportin liitteeksi.',
    'sv' => 'Här kan du lägga till preciserande texter som inte får plats i den egentliga Safetyflash-bilden. Dessa uppgifter skrivs automatiskt ut som bilaga till PDF-rapporten.',
    'en' => 'Here you can add clarifying texts that do not fit in the actual Safetyflash image. This information will automatically be printed as an appendix to the PDF report.',
    'it' => 'Qui puoi aggiungere testi esplicativi che non rientrano nell\'immagine Safetyflash. Queste informazioni verranno automaticamente stampate come allegato al report PDF.',
    'el' => 'Εδώ μπορείτε να προσθέσετε διευκρινιστικά κείμενα που δεν χωρούν στην εικόνα Safetyflash. Αυτές οι πληροφορίες θα εκτυπωθούν αυτόματα ως παράρτημα στην αναφορά PDF.',
],
'additional_info_placeholder' => [
    'fi' => 'Kirjoita lisätietoja tapahtumasta...',
    'sv' => 'Skriv ytterligare information om händelsen...',
    'en' => 'Write additional information about the event...',
    'it' => 'Scrivi informazioni aggiuntive sull\'evento...',
    'el' => 'Γράψτε πρόσθετες πληροφορίες για το συμβάν...',
],
'additional_info_add_btn' => [
    'fi' => 'Lisää teksti',
    'sv' => 'Lägg till text',
    'en' => 'Add text',
    'it' => 'Aggiungi testo',
    'el' => 'Προσθήκη κειμένου',
],
'additional_info_saved' => [
    'fi' => 'Tallennettu',
    'sv' => 'Sparat',
    'en' => 'Saved',
    'it' => 'Salvato',
    'el' => 'Αποθηκεύτηκε',
],
'additional_info_save_error' => [
    'fi' => 'Tallennus epäonnistui',
    'sv' => 'Fel vid sparning',
    'en' => 'Save failed',
    'it' => 'Salvataggio non riuscito',
    'el' => 'Αποτυχία αποθήκευσης',
],
'additional_info_unknown_author' => [
    'fi' => 'Tuntematon',
    'sv' => 'Okänd',
    'en' => 'Unknown',
    'it' => 'Sconosciuto',
    'el' => 'Άγνωστος',
],
'additional_info_pdf_section' => [
    'fi' => 'Lisätiedot tapahtumasta',
    'sv' => 'Ytterligare information om händelsen',
    'en' => 'Additional information about the event',
    'it' => 'Informazioni aggiuntive sull\'evento',
    'el' => 'Πρόσθετες πληροφορίες για το συμβάν',
],
'additional_info_modal_add_title' => [
    'fi' => 'Lisää teksti',
    'sv' => 'Lägg till text',
    'en' => 'Add text',
    'it' => 'Aggiungi testo',
    'el' => 'Προσθήκη κειμένου',
],
'additional_info_modal_edit_title' => [
    'fi' => 'Muokkaa tekstiä',
    'sv' => 'Redigera text',
    'en' => 'Edit text',
    'it' => 'Modifica testo',
    'el' => 'Επεξεργασία κειμένου',
],
'badge_athena_exported' => [
    'fi' => 'Tallennettu Athenaan',
    'sv' => 'Sparad i Athena',
    'en' => 'Saved to Athena',
    'it' => 'Salvato su Athena',
    'el' => 'Αποθηκεύτηκε στο Athena',
],
'badge_athena_exported_by' => [
    'fi' => 'Viety',
    'sv' => 'Exporterad',
    'en' => 'Exported',
    'it' => 'Esportato',
    'el' => 'Εξαγμένο',
],
'badge_athena_action_export' => [
    'fi' => 'Lataa PDF Athenaa varten',
    'sv' => 'Ladda ned PDF för Athena',
    'en' => 'Download PDF for Athena',
    'it' => 'Scarica PDF per Athena',
    'el' => 'Λήψη PDF για Athena',
],
'badge_athena_action_already_exported' => [
    'fi' => 'Olen jo vienyt Athenaan',
    'sv' => 'Jag har redan exporterat till Athena',
    'en' => 'I already exported it to Athena',
    'it' => 'L\'ho già esportato su Athena',
    'el' => 'Το έχω ήδη εξαγάγει στο Athena',
],
'badge_athena_not_exported' => [
    'fi' => 'Ei vielä Athenassa',
    'sv' => 'Inte ännu i Athena',
    'en' => 'Not yet in Athena',
    'it' => 'Non ancora in Athena',
    'el' => 'Δεν είναι ακόμη στο Athena',
],
'btn_athena_mark_done' => [
    'fi' => 'Merkitse tallennetuksi',
    'sv' => 'Markera som sparad',
    'en' => 'Mark as saved',
    'it' => 'Segna come salvato',
    'el' => 'Σημείωσε ως αποθηκευμένο',
],
'log_worksite_notification_sent' => [
    'fi' => 'Työmaailmoitus lähetetty',
    'sv' => 'Arbetsplatsmeddelande skickat',
    'en' => 'Worksite notification sent',
    'it' => 'Notifica del cantiere inviata',
    'el' => 'Η ειδοποίηση εργοταξίου στάλθηκε',
],
'btn_clear_all' => [
    'fi' => 'Tyhjennä valinnat',
    'sv' => 'Rensa val',
    'en' => 'Clear selections',
    'it' => 'Cancella selezioni',
    'el' => 'Εκκαθάριση επιλογών',
],
	'workflow_progress_title' => [
    'fi' => 'Prosessin eteneminen',
    'sv' => 'Processens framskridande',
    'en' => 'Process progress',
    'it' => 'Avanzamento del processo',
    'el' => 'Πρόοδος διαδικασίας',
],
'workflow_progress_description' => [
    'fi' => 'Koko tapahtuman eteneminen alkuperäisestä tiedotteesta lopulliseen tutkintatiedotteeseen.',
    'sv' => 'Hela händelsens framskridande från det ursprungliga meddelandet till den slutliga utredningsrapporten.',
    'en' => 'The full event lifecycle from the original notice to the final investigation report.',
    'it' => 'L’intero ciclo dell’evento dalla segnalazione originale al rapporto di indagine finale.',
    'el' => 'Ο πλήρης κύκλος ζωής του συμβάντος από την αρχική ειδοποίηση έως την τελική αναφορά διερεύνησης.',
],
'workflow_phase_original_subtitle' => [
    'fi' => 'Alkuperäinen tapahtumatiedote',
    'sv' => 'Ursprungligt händelsemeddelande',
    'en' => 'Original event notice',
    'it' => 'Segnalazione evento originale',
    'el' => 'Αρχική ειδοποίηση συμβάντος',
],
'workflow_phase_investigation_subtitle' => [
    'fi' => 'Jatkaa samaa tapahtumaa tutkintatiedotteena',
    'sv' => 'Fortsätter samma händelse som en utredningsrapport',
    'en' => 'Continues the same event as an investigation report',
    'it' => 'Prosegue lo stesso evento come rapporto di indagine',
    'el' => 'Συνεχίζει το ίδιο συμβάν ως αναφορά διερεύνησης',
],
'workflow_phase_standalone_investigation_subtitle' => [
    'fi' => 'Tutkinta aloitettu ilman aiempaa ensitiedotetta tai vaaratilannetiedotetta',
    'sv' => 'Utredningen har startats utan tidigare första meddelande eller tillbudsmeddelande',
    'en' => 'Investigation started without a previous first release or dangerous situation notice',
    'it' => 'Indagine avviata senza una precedente prima comunicazione o segnalazione di situazione pericolosa',
    'el' => 'Η διερεύνηση ξεκίνησε χωρίς προηγούμενη αρχική ειδοποίηση ή ειδοποίηση επικίνδυνης κατάστασης',
],
'workflow_status_completed' => [
    'fi' => 'Valmis',
    'sv' => 'Klar',
    'en' => 'Completed',
    'it' => 'Completato',
    'el' => 'Ολοκληρώθηκε',
],
'workflow_step_created' => [
    'fi' => 'Luotu',
    'sv' => 'Skapad',
    'en' => 'Created',
    'it' => 'Creato',
    'el' => 'Δημιουργήθηκε',
],
'workflow_step_supervisor' => [
    'fi' => 'Työmaavastaava',
    'sv' => 'Platsansvarig',
    'en' => 'Site supervisor',
    'it' => 'Responsabile del sito',
    'el' => 'Υπεύθυνος εργοταξίου',
],
'workflow_step_safety' => [
    'fi' => 'Turvatiimi',
    'sv' => 'Säkerhetsteam',
    'en' => 'Safety team',
    'it' => 'Team sicurezza',
    'el' => 'Ομάδα ασφάλειας',
],
'workflow_step_comms' => [
    'fi' => 'Viestintä',
    'sv' => 'Kommunikation',
    'en' => 'Communications',
    'it' => 'Comunicazione',
    'el' => 'Επικοινωνία',
],
'workflow_step_published' => [
    'fi' => 'Julkaistu',
    'sv' => 'Publicerad',
    'en' => 'Published',
    'it' => 'Pubblicato',
    'el' => 'Δημοσιεύτηκε',
],
'workflow_tooltip_done' => [
    'fi' => 'Vaihe valmis',
    'sv' => 'Steget är klart',
    'en' => 'Step completed',
    'it' => 'Fase completata',
    'el' => 'Το βήμα ολοκληρώθηκε',
],
'workflow_tooltip_active' => [
    'fi' => 'Nykyinen vaihe',
    'sv' => 'Aktuellt steg',
    'en' => 'Current step',
    'it' => 'Fase corrente',
    'el' => 'Τρέχον βήμα',
],
'workflow_tooltip_pending' => [
    'fi' => 'Ei vielä suoritettu',
    'sv' => 'Inte utfört ännu',
    'en' => 'Not completed yet',
    'it' => 'Non ancora completato',
    'el' => 'Δεν έχει ολοκληρωθεί ακόμη',
],
'workflow_tooltip_time' => [
    'fi' => 'Aika',
    'sv' => 'Tid',
    'en' => 'Time',
    'it' => 'Ora',
    'el' => 'Ώρα',
],
'workflow_tooltip_user' => [
    'fi' => 'Käsittelijä',
    'sv' => 'Behandlare',
    'en' => 'Handled by',
    'it' => 'Gestito da',
    'el' => 'Χειριστής',
],
'workflow_tooltip_user_missing' => [
    'fi' => 'Käsittelijää ei ole vielä määritetty',
    'sv' => 'Ingen behandlare har ännu angetts',
    'en' => 'No handler recorded yet',
    'it' => 'Nessun responsabile ancora registrato',
    'el' => 'Δεν έχει καταγραφεί χειριστής ακόμη',
],
	'workflow_target_system' => [
    'fi' => 'Järjestelmä',
    'sv' => 'System',
    'en' => 'System',
    'it' => 'Sistema',
    'el' => 'Σύστημα',
],
'workflow_target_supervisor' => [
    'fi' => 'Työmaavastaava',
    'sv' => 'Platsansvarig',
    'en' => 'Site supervisor',
    'it' => 'Responsabile del sito',
    'el' => 'Υπεύθυνος εργοταξίου',
],
'workflow_target_safety' => [
    'fi' => 'Turvatiimi',
    'sv' => 'Säkerhetsteam',
    'en' => 'Safety team',
    'it' => 'Team sicurezza',
    'el' => 'Ομάδα ασφάλειας',
],
'workflow_target_comms' => [
    'fi' => 'Viestintä',
    'sv' => 'Kommunikation',
    'en' => 'Communications',
    'it' => 'Comunicazione',
    'el' => 'Επικοινωνία',
],
'workflow_target_published' => [
    'fi' => 'Julkaisu',
    'sv' => 'Publicering',
    'en' => 'Publishing',
    'it' => 'Pubblicazione',
    'el' => 'Δημοσίευση',
],
'workflow_tooltip_target' => [
    'fi' => 'Vastaanottaja',
    'sv' => 'Mottagare',
    'en' => 'Recipient',
    'it' => 'Destinatario',
    'el' => 'Παραλήπτης',
],
'workflow_tooltip_started' => [
    'fi' => 'Vaihe aloitettu',
    'sv' => 'Steget startade',
    'en' => 'Step started',
    'it' => 'Fase avviata',
    'el' => 'Το βήμα ξεκίνησε',
],
'workflow_tooltip_delivered_by' => [
    'fi' => 'Toimittaja',
    'sv' => 'Skickat av',
    'en' => 'Sent by',
    'it' => 'Inviato da',
    'el' => 'Απεστάλη από',
],
'workflow_tooltip_delivered_by_missing' => [
    'fi' => 'Toimittajaa ei ole kirjattu',
    'sv' => 'Avsändare har inte registrerats',
    'en' => 'Sender not recorded',
    'it' => 'Mittente non registrato',
    'el' => 'Ο αποστολέας δεν έχει καταγραφεί',
],
'workflow_tooltip_handled' => [
    'fi' => 'Käsitelty',
    'sv' => 'Behandlat',
    'en' => 'Handled',
    'it' => 'Gestito',
    'el' => 'Διεκπεραιώθηκε',
],
'workflow_tooltip_handled_by' => [
    'fi' => 'Käsittelijä',
    'sv' => 'Behandlare',
    'en' => 'Handled by',
    'it' => 'Gestito da',
    'el' => 'Χειριστής',
],
'workflow_tooltip_handled_by_missing' => [
    'fi' => 'Käsittelijää ei ole vielä kirjattu',
    'sv' => 'Behandlare har ännu inte registrerats',
    'en' => 'Handler not recorded yet',
    'it' => 'Responsabile non ancora registrato',
    'el' => 'Δεν έχει καταγραφεί ακόμη χειριστής',
],
	'workflow_tooltip_created' => [
    'fi' => 'Luotu',
    'sv' => 'Skapad',
    'en' => 'Created',
    'it' => 'Creato',
    'el' => 'Δημιουργήθηκε',
],
'workflow_tooltip_approved' => [
    'fi' => 'Hyväksytty',
    'sv' => 'Godkänd',
    'en' => 'Approved',
    'it' => 'Approvato',
    'el' => 'Εγκρίθηκε',
],
'workflow_tooltip_published' => [
    'fi' => 'Julkaistu',
    'sv' => 'Publicerad',
    'en' => 'Published',
    'it' => 'Pubblicato',
    'el' => 'Δημοσιεύτηκε',
],
'workflow_tooltip_sent_to_comms' => [
    'fi' => 'Toimitettu viestinnälle',
    'sv' => 'Skickad till kommunikation',
    'en' => 'Sent to communications',
    'it' => 'Inviato alla comunicazione',
    'el' => 'Στάλθηκε στην επικοινωνία',
],
	'workflow_tooltip_skipped' => [
    'fi' => 'Ohitettu',
    'sv' => 'Hoppades över',
    'en' => 'Skipped',
    'it' => 'Saltato',
    'el' => 'Παραλείφθηκε',
],
	'footer_language_review' => [
    'fi' => 'Pyydä kielitarkistus',
    'sv' => 'Begär språkgranskning',
    'en' => 'Request language review',
    'it' => 'Richiedi revisione linguistica',
    'el' => 'Αίτημα γλωσσικού ελέγχου',
],
'language_review_modal_title' => [
    'fi' => 'Pyydä kieliversioiden tarkistus',
    'sv' => 'Begär granskning av språkversioner',
    'en' => 'Request review of language versions',
    'it' => 'Richiedi revisione delle versioni linguistiche',
    'el' => 'Αίτημα ελέγχου γλωσσικών εκδόσεων',
],
'language_review_modal_help' => [
    'fi' => 'Valitse kieliversioille tarkistajat. Tarkistaja saa oikeuden nähdä SafetyFlashin, muokata omaa kieliversiotaan ja julkaista sen oman maan infonäytöille.',
    'sv' => 'Välj granskare för språkversionerna. Granskaren får rätt att se SafetyFlashen, redigera sin språkversion och publicera den på det egna landets informationsskärmar.',
    'en' => 'Select reviewers for the language versions. The reviewer can view the SafetyFlash, edit their own language version and publish it to their country displays.',
    'it' => 'Seleziona i revisori per le versioni linguistiche. Il revisore può visualizzare il SafetyFlash, modificare la propria versione linguistica e pubblicarla sugli schermi del proprio paese.',
    'el' => 'Επιλέξτε ελεγκτές για τις γλωσσικές εκδόσεις. Ο ελεγκτής μπορεί να δει το SafetyFlash, να επεξεργαστεί τη δική του γλωσσική έκδοση και να τη δημοσιεύσει στις οθόνες της χώρας του.',
],
'language_review_select_reviewer' => [
    'fi' => 'Tarkistaja',
    'sv' => 'Granskare',
    'en' => 'Reviewer',
    'it' => 'Revisore',
    'el' => 'Ελεγκτής',
],
'language_review_search_placeholder' => [
    'fi' => 'Hae henkilöä nimellä tai sähköpostilla...',
    'sv' => 'Sök person med namn eller e-post...',
    'en' => 'Search by name or email...',
    'it' => 'Cerca per nome o e-mail...',
    'el' => 'Αναζήτηση με όνομα ή email...',
],
'language_review_can_publish' => [
    'fi' => 'Saa julkaista',
    'sv' => 'Får publicera',
    'en' => 'Can publish',
    'it' => 'Può pubblicare',
    'el' => 'Μπορεί να δημοσιεύσει',
],
'language_review_send_requests' => [
    'fi' => 'Lähetä tarkistuspyynnöt',
    'sv' => 'Skicka granskningsbegäran',
    'en' => 'Send review requests',
    'it' => 'Invia richieste di revisione',
    'el' => 'Αποστολή αιτημάτων ελέγχου',
],
'language_review_select_at_least_one' => [
    'fi' => 'Valitse vähintään yksi tarkistaja.',
    'sv' => 'Välj minst en granskare.',
    'en' => 'Select at least one reviewer.',
    'it' => 'Seleziona almeno un revisore.',
    'el' => 'Επιλέξτε τουλάχιστον έναν ελεγκτή.',
],
'language_review_sending' => [
    'fi' => 'Lähetetään...',
    'sv' => 'Skickar...',
    'en' => 'Sending...',
    'it' => 'Invio...',
    'el' => 'Αποστολή...',
],
'language_review_requested_success' => [
    'fi' => 'Kielitarkistuspyynnöt lähetettiin.',
    'sv' => 'Begäran om språkgranskning skickades.',
    'en' => 'Language review requests were sent.',
    'it' => 'Le richieste di revisione linguistica sono state inviate.',
    'el' => 'Τα αιτήματα γλωσσικού ελέγχου στάλθηκαν.',
],
'language_review_no_assignments' => [
    'fi' => 'Yhtään tarkistuspyyntöä ei voitu tallentaa.',
    'sv' => 'Ingen granskningsbegäran kunde sparas.',
    'en' => 'No review request could be saved.',
    'it' => 'Non è stato possibile salvare alcuna richiesta di revisione.',
    'el' => 'Δεν ήταν δυνατή η αποθήκευση κανενός αιτήματος ελέγχου.',
],
'language_review_email_subject' => [
    'fi' => 'SafetyFlash-kielitarkistus: {title}',
    'sv' => 'SafetyFlash språkgranskning: {title}',
    'en' => 'SafetyFlash language review: {title}',
    'it' => 'Revisione linguistica SafetyFlash: {title}',
    'el' => 'Γλωσσικός έλεγχος SafetyFlash: {title}',
],
'language_review_message_label' => [
    'fi' => 'Saateviesti',
    'sv' => 'Meddelande',
    'en' => 'Message',
    'it' => 'Messaggio',
    'el' => 'Μήνυμα',
],
'language_review_message_placeholder' => [
    'fi' => 'Kirjoita tarvittaessa tarkistajille lyhyt ohje tai lisätieto...',
    'sv' => 'Skriv vid behov en kort instruktion eller tilläggsinformation till granskarna...',
    'en' => 'Add a short instruction or additional note for the reviewers if needed...',
    'it' => 'Aggiungi se necessario una breve istruzione o una nota per i revisori...',
    'el' => 'Προσθέστε σύντομη οδηγία ή επιπλέον σημείωση για τους ελεγκτές, αν χρειάζεται...',
],
'language_review_message_email_heading' => [
    'fi' => 'Saateviesti',
    'sv' => 'Meddelande',
    'en' => 'Message',
    'it' => 'Messaggio',
    'el' => 'Μήνυμα',
],
'language_review_email_body_text' => [
    'fi' => "Sinulle on osoitettu SafetyFlashin kielitarkistus.\n\nTarkistettava kieliversio: {language}",
    'sv' => "Du har tilldelats en språkgranskning för en SafetyFlash.\n\nSpråkversion att granska: {language}",
    'en' => "You have been assigned a SafetyFlash language review.\n\nLanguage version to review: {language}",
    'it' => "Ti è stata assegnata una revisione linguistica di SafetyFlash.\n\nVersione linguistica da controllare: {language}",
    'el' => "Σας έχει ανατεθεί γλωσσικός έλεγχος SafetyFlash.\n\nΓλωσσική έκδοση για έλεγχο: {language}",
],
'language_review_language_sv' => [
    'fi' => 'Ruotsi',
    'sv' => 'Svenska',
    'en' => 'Swedish',
    'it' => 'Svedese',
    'el' => 'Σουηδικά',
],
'language_review_language_en' => [
    'fi' => 'Englanti',
    'sv' => 'Engelska',
    'en' => 'English',
    'it' => 'Inglese',
    'el' => 'Αγγλικά',
],
'language_review_language_it' => [
    'fi' => 'Italia',
    'sv' => 'Italienska',
    'en' => 'Italian',
    'it' => 'Italiano',
    'el' => 'Ιταλικά',
],
'language_review_language_el' => [
    'fi' => 'Kreikka',
    'sv' => 'Grekiska',
    'en' => 'Greek',
    'it' => 'Greco',
    'el' => 'Ελληνικά',
],
	'language_review_current_section_title' => [
    'fi' => 'Kielitarkistaja',
    'sv' => 'Språkgranskare',
    'en' => 'Language reviewer',
    'it' => 'Revisore linguistico',
    'el' => 'Ελεγκτής γλώσσας',
],
'language_review_current_language' => [
    'fi' => 'Kieliversio',
    'sv' => 'Språkversion',
    'en' => 'Language version',
    'it' => 'Versione linguistica',
    'el' => 'Γλωσσική έκδοση',
],
'language_review_current_can_publish' => [
    'fi' => 'Saa julkaista kieliversion',
    'sv' => 'Får publicera språkversionen',
    'en' => 'Can publish the language version',
    'it' => 'Può pubblicare la versione linguistica',
    'el' => 'Μπορεί να δημοσιεύσει τη γλωσσική έκδοση',
],
'language_review_comment_badge' => [
    'fi' => 'Kielitarkistus',
    'sv' => 'Språkgranskning',
    'en' => 'Language review',
    'it' => 'Revisione linguistica',
    'el' => 'Γλωσσικός έλεγχος',
],
'log_language_review_comment' => [
    'fi' => 'Kielitarkistuksen saateviesti',
    'sv' => 'Meddelande för språkgranskning',
    'en' => 'Language review message',
    'it' => 'Messaggio per la revisione linguistica',
    'el' => 'Μήνυμα γλωσσικού ελέγχου',
],
];